### ISSUE TITLE
UML Diagrams

### ISSUE THREAD

**Issue by hrishikeshpaul** [airavata-courses/scrapbook#3]
Use Case Diagram

Activity Diagram

**Comment by chirag-indi** [comment]
![image](https://user-images.githubusercontent.com/20301919/106998354-5d95a700-6752-11eb-9095-31743a55fb24.png)

@hrishikeshpaul @jbhushan791 Please review and let me know if any changes need to be made.

**Comment by hrishikeshpaul** [comment]
This diagram shows that a "Viewer" can share images (which isn't the case). The only thing common between ALL the 3 roles of a user is the fact that they can,
- login
- view images
- view notifications
- view metrics

Whereas, a viewer **cannot** give access, revoke access, delete, edit albums/images (you've missed out the edit/delete part). Take a look at the meeting notes for further reference as to what we discussed. When you're deriving a user, make sure you're deriving it from an absolute BASE case. For example take a look at this diagram, 

![Use-Case-Diagram-Sample](https://user-images.githubusercontent.com/22999894/107051145-17fccc80-679a-11eb-8c92-59695fe19573.png)

Let me know if it makes sense. Thanks!

**Comment by chirag-indi** [comment]
The primary reason, I derived all three roles with the common functionality was to emphasize the fact that each role is NOT absolute, i.e. it varies from folder to folder. The same user will/can have all three roles simultaneously in a single session. To clarify, these are set at a folder level and not at the user level. In the above Use Case diagram that you have linked a member can NOT be a General member and a Premium Member at the same point in time.

And with respect to the "Viewer can not give access part" extending use case typically defines optional behavior. So I believe it would change depending on how we choose to implement the use case. I agree that the Grant/Revoke access needs to have an arrow pointing to Verify Role and I have added that in the below diagram. Since we do not have an edit functionality, I have added only delete uploaded photos as a new case. I have added another use case of search which I had missed initially. 

Please correct me if my understanding of this is wrong.

 
![image](https://user-images.githubusercontent.com/20301919/107059906-5ac3a200-67a4-11eb-817a-47e5e971ba2e.png)

**Comment by hrishikeshpaul** [comment]
I see what you mean. But with a user case diagram we generally define the "role" what a user plays WITHIN a specified scope. You're correct, that the roles are based on an album level. But look at it from an album level. Can a user be an owner, collaborator and viewer? Or think about it this way, can a viewer be a collaborator and a viewer at the same *for a specific folder*? Like you said "*In the above Use Case diagram that you have linked a member can NOT be a General member and a Premium Member at the same point in time*", which is absolutely right. In that example the scope is from an account perspective. Here we're trying to see the scope for an album perspective. 

So if you just restrict this above diagram to ONLY an album, is it correct that a viewer gets to delete uploaded images? Right now the issue with the diagram is that all the users seem to be the same (have the same powers), which is true if you look at it from an account level (yes, a viewer can be the owner of another album, and simultaneously be a collaborator in another album). But that doesn't help us to DEFINE the roles. Ultimately, all of this is just to help us code at the end, so if you look at this diagram, atleast to me, all the users look to be the same - even if you look at it from the scope of an album. 

Like in the example above that I shared, you have a Member, who can watch stuff. The General Member AND the Premium member can watch the same things, except, each of them have a different ability based on who they are. While it's true that in that example that a user can't have both permissions, but through that example there is a clear hierarchy wtr to an account. In our case, **our scope is the album, so looking at an album, an user can only be one thing at a period of time.**

"*Since we do not have an edit functionality*" - we can rename images/album right? I thought we discussed this, I'm not sure.

Let me know if this makes sense.

**Comment by chirag-indi** [comment]
I was considering the system point of view, but what you say makes complete sense while looking at individual albums. 

"we can rename images/album right?" - Didn't think rename was synonymous with edit and was considered as a significant feature to be mentioned in the point of view of a Distributed Systems class. 

I have updated the Use Case diagram, please let me know if any more changes are necessary.

![image](https://user-images.githubusercontent.com/20301919/107102974-05aa7f00-67ea-11eb-998d-7793c9132a30.png)

**Comment by hrishikeshpaul** [comment]
Oh, I was under the impression that renaming is an edit. I mean of we don't want to have it I'm cool! 

But this looks good to me! I think this alone will really help us later when were like coding it, because now we're all on the same page! Good work 😁

**Comment by hrishikeshpaul** [comment]
@chirag-indi I added this to the latest commit in the PR #15 so I think we can close this
